function boltATK(attacker: entity, itemID: text):
	set {_location} to location 0.5 blocks below {_attacker}'s head
	play sound "item.trident.riptide_1" with pitch 1.2 at {_attacker}
	loop {_range} times:
		loop 2 times:
			draw 1 of dust using dustOption(white, 1) at {_location} ~ {_v} with extra 0.0
			loop all entities in radius 0.8 of location 0.5 block below {_location}:
				if damageCheck({_attacker}, loop-entity) is true:
					if {_tagged::*} does not contain loop-entity:
						damage loop-entity by getDamage({_attacker}, loop-entity, {_damage})
						add loop-entity to {_tagged::*}
						loop 10 times:
							draw 1 of electric spark at loop-entity's head with extra 1
			set {_location} to location 0.5 block in front of {_location}
	
	
	