command /debugMode:
	permission: op
	trigger:
		if {p::false::%player%::debug} is not set:
			set {p::false::%player%::debug} to true
			send "&7You will now recieve debugging information for multiple occassions."
		else:
			clear {p::false::%player%::debug}
			send "&7You will no longer recieve debugging information for multiple occassions."

command /debugstats:
	permission: op
	trigger:
		send "Armor Attribute %player's generic armor attribute%"
		send "endurance %{p::false::%player%::endurance}%"
		send "Health %Player's health*2%/%player's max health attribute%"
		send "regeneration %{p::false::%player%::regeneration}%"
		send "Speed %player's generic movement speed attribute%"
		send "Strength %{p::false::%player%::strength}%"
		send "Damage %player's generic attack damage attribute%"
		send "Mysticism %{p::false::%player%::mysticism}%"
		send "XP bonus %{p::false::%player%::experience}%"
		send "Cash Bonus %{p::false::%player%::scavenger}%"
		send "Luck %{p::false::%player%::luck}%"
